version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./api
    ports:
      - "5000:5000" # Flask roda na porta 5000 por padrão
    environment:
      # Para Celery saber onde está o Redis (broker e backend)
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./api:/app # Mapeia o código da API para dentro do container para live reload (desenvolvimento)

  worker:
    build: ./worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./worker:/app # Mapeia o código do worker para dentro do container para live reload (desenvolvimento)

volumes:
  redis_data: